SELECT COUNT(*) FROM (SELECT DISTINCT Vendor FROM CPEs WHERE Vendor  LIKE '%[_]%')b
SELECT COUNT(*) FROM (SELECT DISTINCT Vendor FROM CPEs)c

SELECT COUNT(*) FROM (SELECT DISTINCT Product FROM CPEs WHERE Product  LIKE '%[_]%')b
SELECT COUNT(*) FROM (SELECT DISTINCT Product FROM CPEs)c

