IF NOT EXISTS(SELECT 1 FROM sys.tables WHERE name = 'CPEs')
BEGIN
	CREATE TABLE CPEs(
		Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
		[Name] NVARCHAR(100),
		[Title] NVARCHAR(100),
		Part NVARCHAR(100),
		Vendor NVARCHAR(100),
		Product NVARCHAR(100),
		[Version] NVARCHAR(100),
		[Update] NVARCHAR(100),
		Edition NVARCHAR(100),
		[Language] NVARCHAR(100),
		Sw_edition NVARCHAR(100),
		Target_sw NVARCHAR(100),
		Target_hw NVARCHAR(100),
		Other NVARCHAR(100),

	);
END





